### PR TITLE
Adding new example for circuitpython requests_https

### PR DESCRIPTION
**Pull request by jfabernathy**
I've been asked to add my example to the directory of example. It's uses requests_https on circuitpython and has been tested on an Adafruit Metro ESP32 Express

### CODE REVIEW

**Comment by ladyada** [comment]
hihi looks like needs a copyright notice at the top, maybe `black` and `pylint` - do ya know how to do those?

**Comment by jfabernathy** [comment]
Sorry not sure what they are or how to fix it now that the code on my end has been committed and pushed.  It was amazing that I got that for. I'm guessing that you have a generic copyright that can be inserted.  What happen is someone pointed me to an example that wouldn't work and I fixed it. I uploaded that to the forum for anyone interested.  Someone asked me to put it on github.  Turned out that the example was really for python on a raspberry pi using the blinka library.  So here we are.  The is where I was told to post the example this time. I was able to fork, clone, add the file commit and push.  That's about all this 70 year old can do.

**Comment by ladyada** [comment]
ha ok @dherrada can help you out with the rest, you're really close!

**Comment by dherrada** [comment]
@jfabernathy Ok, so it looks like you're currently failing two of the pre-commit checks.

The first one is the black check. This one is pretty easy to fix. Basically install black with `pip install black` and then run it in your directory with `black --target-version=py35 .` .

Now, you also added a file, so you're gonna need to add a license to it. I'd just copy the text from the other example files and change the name to your name and possibly the year if it isn't 2021. 

Let me know if you've got a

**Comment by dherrada** [comment]
@jfabernathy This is the license for examples. Since you're adding a new one that you wrote, replace ladyada with your name (can be either your GitHub name or your actual name). Looks like your fork was made before I added them to this library which makes sense as to why you didn't see them.
```
# SPDX-FileCopyrightText: 2021 ladyada for Adafruit Industries
# SPDX-License-Identifier: MIT
```

**Comment by jfabernathy** [comment]
after I added the License statements I committed and pushed.  It failed again and I finally found out why.  pylint really doesn't like my import statements and I have no idea why. The code runs fine.

**Comment by anecdata** [comment]
@jfabernathy the details of what `pylint` is failing is here: <https://github.com/adafruit/Adafruit_CircuitPython_Requests/pull/68/checks?check_run_id=1826084237> It's not necessarily "right", but you can re-sequence the imports as it suggests and see if that makes it happy.

**Comment by jfabernathy** [comment]
I've made progress but still failing with one error, exit code 1.  So not sure what to do. imports seem fine now.

**Comment by anecdata** [comment]
I'm not sure about that one, maybe dherrada can advise.

**Comment by askpatrickw** [comment]
If pre-commit finds anything it will exit that way.
https://github.com/adafruit/Adafruit_CircuitPython_Requests/pull/68/checks?check_run_id=1826367683#step:11:24
At that line, you can see that black wanted to reformat a file.
One more run of black locally and then commit that file. 

Whew... I know. ;-) But you got this !

**Comment by jfabernathy** [comment]
I ran black again, added, committed, and pushed again. It didn't reject this time. Only good news about this process is it will drive you to drink :-)

**Comment by dherrada** [comment]
@jfabernathy Great to see that it's passing!

**Review by brentru — APPROVED** [review]

**Review by anecdata — APPROVED** [review]
Tested successfully on FeatherS2. Thanks for sticking with it @jfabernathy!

**Comment by dherrada** [comment]
Merging since we've got 2 approvals

**Pull request merged**
