### PR TITLE
Update OpenSky-Network Public Single Flight API Example

### PR DESCRIPTION
**Pull request by DJDevon3**
Public API, no credentials required. Instructions in code comments. Less daily calls than Private API.

Added
- pretty serial hierarchy view
- general code cleanup and improvements
- improved endpoints with server side failure messages
- improved and streamlined debugging
- shouty constants to make Pylint happy.
- imports sorted
- doc strings for functions
- uses settings.toml by default
- using Connection Manager by default

Serial output example:
```
Connecting to WiFi...
✅ Wifi!
 | Attempting to GET OpenSky-Network Single Public Flight JSON!
 | Website Credentials NOT Required! Less daily calls than Private.
 | ✅ OpenSky-Network Public JSON!
 |  | Last Contact: 03/19/2024 10:05:55
 |  | Transponder: 88044d
 |  | Callsign: AIQ351  
 |  | Squawk: None
 |  | Origin: Thailand
 |  | Longitude: 100.836
 |  | Latitude: 12.3921
 |  | Barometric Altitude: 8572.5
 |  | Velocity: 224.03
 |  | Vertical Rate: 2.6
✂️ Disconnected from OpenSky-Network API

Finished!
Board Uptime: 1.2 days
Next Update: 30 minutes
===============================
```

### CODE REVIEW

**Comment by DJDevon3** [comment]
This was the PR that I accidentally merged with the private example.  Everything should be all good now.

**Comment by DJDevon3** [comment]
@FoamyGuy This one is good to go as well.

**Comment by FoamyGuy** [comment]
@DJDevon3 There are merge conflicts that prevent merge on this one. It looks to me like the same changes were already brought in from #167 

Were there any specific other changes in this one?

**Comment by DJDevon3** [comment]
@FoamyGuy 167 is the private example and this one (172) is the public example.  Don't worry about it I can go back through commit history if necessary and repull the right one if it gets lost and recommit.

**Comment by FoamyGuy** [comment]
#167 contained changes to both public and private, I know it wasn't the original intent, but those changes were there. You can see the list of changes here: https://github.com/adafruit/Adafruit_CircuitPython_Requests/pull/167/files

**Comment by DJDevon3** [comment]
@FoamyGuy The private example here has been updated with the most recent merged version (merged previously today).  Merging it again should have no effect as it should be the same file.  I updated the "Coded for" section to Circuit Python 9.x

I made sure the public example here is the correct public single flight example and is good to merge.

This PR can merge both now with no conflicts or at least the intention is cleaned up in both of these files now.

**Review by FoamyGuy — APPROVED** [review]
I merged main and resolved the conflicts locally then pushed the result to this branch.  I think the main part it was having trouble with was the version numbers at the top of the files in the comments.

These changes are looking good to me now. I tested the updated public example on a feather S3 TFT

**Pull request merged**
