### PR TITLE
Update Open-Sky Network Private Area API Example 

### PR DESCRIPTION
**Pull request by DJDevon3**
Private API, website credentials required. Instructions in code comments. More daily calls than Public API.
Pulls flight data from a geographic area. Example is around Orlando airport.

Added
- pretty serial hierarchy view
- general code cleanup and improvements
- improved endpoints with server side failure messages
- improved and streamlined debugging
- shouty constants to make Pylint happy.
- imports sorted
- switched from circuitpython_base64 to adafruit_binascii for base64 credential encoding
- doc strings for functions
- uses settings.toml by default
- now using Connection Manager by default

Changed from circuitpython_base64 community library to adafruit_binascii. It encodes to base64 much faster and has Adafruit library support.  It's a better way to go for examples needing base64 encoding.

Serial output example:
```
Connecting to WiFi...
✅ Wifi!
 | Attempting to GET OpenSky-Network Area Flights JSON!
 | ✅ OpenSky-Network JSON!
 |  | Timestamp: 03/18/2024 07:00:20
 |  | Trans:ad4804 Sign:JBU2523 Origin:United States Time:1710744961 Last:1710744961 Lon:-81.327 Lat:28.4545 BaroAlt:83.82 Ground:False Vel:69.97 Head:179.16 VertRate:-3.58 Sens:None GeoAlt:68.58 Squawk:0501 Task:False PosSys:0 Cat:0 
 |  | Trans:a05087 Sign:GTX508  Origin:United States Time:1710745220 Last:1710745220 Lon:-81.4167 Lat:28.7626 BaroAlt:914.4 Ground:False Vel:80.53 Head:154.25 VertRate:0 Sens:None GeoAlt:906.78 Squawk:None Task:False PosSys:0 Cat:0 
✂️ Disconnected from OpenSky-Network API

Finished!
Board Uptime: 1 hours
Next Update: 30 minutes
===============================
```

### CODE REVIEW

**Comment by DJDevon3** [comment]
This example is good to go.  This PR has nothing to do with the issue in the other Open-Sky Network PR.  As long as this one works it's OK to merge this one.

**Comment by DJDevon3** [comment]
Also added .strip to the end of `binascii.b2a_base64(b"" + str(OSN_CREDENTIALS)).strip()` which will strip off the \n.  still have to use slice but it's 2 less characters to slice off.

**Comment by DJDevon3** [comment]
Double checked the other PR's.  This one is ready for review.

**Review by FoamyGuy — CHANGES_REQUESTED** [review]
Lets change this one also to use `encode()` and `decode()`. There are some diffs in comments in https://github.com/adafruit/Adafruit_CircuitPython_Requests/pull/167 that show the required changes for that.

**Review by FoamyGuy — APPROVED** [review]
Looks good to me. Thank you!

**Pull request merged**
