### PR TITLE
Create requests_wifi_adafruit_status.py

### PR DESCRIPTION
**Pull request by DJDevon3**
An API for checking downtime on adafruit services.

Code.py output example

```py
Connecting to WiFi...
📡 Wifi!

Headers:
Request Timestamp: Fri, 23 Aug 2024 19:45:24 GMT
Rate Limit Remaining: 58
Content Type: application/json

JSON: 
Response Status: ok
Total Monitors: 15
 ✅ Monitor: Accounts
 ✅ Monitor: Accounts - Default Queue Latency
 ✅ Monitor: Accounts - Mailer Queue Latency
 ✅ Monitor: Accounts - Profiles Queue Latency
 ❌ Monitor: Accounts - Queue Retries
 ✅ Monitor: Adafruit Daily
 ✅ Monitor: Blog
 ✅ Monitor: Forums
 ✅ Monitor: IO - API
 ✅ Monitor: IO - Default Queue Latency
 ✅ Monitor: IO - MQTT
 ✅ Monitor: IO - Primary Queue Latency
 ✅ Monitor: IO - Web
 ✅ Monitor: Learn
 ✅ Monitor: Shop
```

Capture

### CODE REVIEW

**Comment by DJDevon3** [comment]
I have no idea if this will work every day or if the api url is only for today.  Issue came up today where Adafruit posted a link to their status page.  https://www.adafruitstatus.com/ So obviously I was curious about the API running it and came up with a quick example for requests that seems to work.

**Review by tannewt — CHANGES_REQUESTED** [review]
I think an adafruit-playground.com would be a better place for this. Going forwards we'll want example code to demonstrate unique features of a library instead of external things such as unique API endpoints.

Maybe we want to add links out to playgrounds instead?

**Comment by DJDevon3** [comment]
I can see how trying to maintain all of the examples whenever there is an API change might require unnecessary time and effort better spent elsewhere for Adafruit staff.  I can host them in a personal repo as I enjoy adding more examples. I'm perfectly fine with that and gives me the added benefit of not having to fight with pylint, black, or ruff. :P

I've made a new repo here: https://github.com/DJDevon3/CircuitPython_Requests-Online-API-Examples 
In the same vein as Todbots Tips & Tricks there comes a time when it's just too much for Adafruit to maintain and I completely understand.  I've saved the examples I wrote so you can reduce or remove the expanded directory if you want.

**Comment by tannewt** [comment]
> I've made a new repo here: https://github.com/DJDevon3/CircuitPython_Requests-Online-API-Examples
> In the same vein as Todbots Tips & Tricks there comes a time when it's just too much for Adafruit to maintain and I completely understand.

Perfect! Thank you!

**Pull request closed without merging**
